version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017

  orderminimalapi:
    build: .
    container_name: api
    ports:
      - 8080:80
      - 8081:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=kestrel_password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/OrderMinimalApi.pfx
      - "OrderDatabase:ConnectionString=mongodb://mongodb:27017"
    volumes:
      - ~/.aspnet/https:/https:ro