services:
  minimalapi:
    build:
      context: .
      dockerfile: ./MinimalApi/Dockerfile
    container_name: minimalapi
    ports:
      - 8080:80
      - 8081:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=kestrel_password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/OrderMinimalApi.pfx
      - Database__ConnectionString=mongodb://mongodb:27017
      - ConnectionStrings__RedisConnection=redis:6379
      - Seq__ConnectionString=http://seq:5341
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
      - order_minimal_api
    depends_on:
      - mongodb
      - redis
      - seq

  mongodb:
    image: mongo:7.0.13-rc0
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    networks:
      - order_minimal_api

  redis:
    image: redis:7.4.0
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - order_minimal_api

  seq:
    image: datalust/seq:2024.3
    container_name: seq
    ports:
      - 5341:80
      - 5342:5342
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq-data:/data
    networks:
      - order_minimal_api

volumes:
  mongodb-data:
  redis-data:
  seq-data:

networks:
  order_minimal_api:
    driver: bridge