version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379

  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - 5341:80
      - 5342:5342
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq-data:/data

  minimalapi:
    build:
      context: .
      dockerfile: ./MinimalApi/Dockerfile
    container_name: minimalapi
    ports:
      - 8080:80
      - 8081:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=kestrel_password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/OrderMinimalApi.pfx
      - OrderDatabase__ConnectionString=mongodb://mongodb:27017
      - ConnectionStrings__RedisConnection=redis:6379
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - mongodb
      - redis
      - seq

volumes:
  seq-data:   