version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017

  minimalapi:
    build:
      context: .
      dockerfile: ./MinimalApi/Dockerfile
    container_name: minimalapi
    ports:
      - 8080:80
      - 8081:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=kestrel_password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/OrderMinimalApi.pfx
      - OrderDatabase__ConnectionString=mongodb://mongodb:27017
    volumes:
      - ~/.aspnet/https:/https:ro